# Generated by Django 3.1 on 2020-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('Student_roll_no', models.CharField(max_length=3)),
                ('student_gender', models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=1)),
                ('Student_add', models.TextField()),
                ('Student_dob', models.DateField()),
                ('Student_std', models.ManyToManyField(to='stud_site.Standar')),
            ],
        ),
    ]
